# Assignment 7

## Submit as an HTML file

### Print your name below

In [57]:
print("Soha Sewani")

Soha Sewani

### Import the "pandas" "numpy" and "statsmodels.formula.api" libraries

In [2]:
# Write your answer here:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

#### In the code chunk below read the CSV file named `results.csv` in the `data` <br> folder and print the first 5 rows of the dataset. Browse the dataset.

In [3]:
results = pd.read_csv("data/results.csv")
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

### (a)  Check Column Types and Data Cleaning

- Use the function .dtypes to get the column types
- Identify which columns have data types that might need conversion
- The 'milliseconds' column contains string values that should be numeric. Create a new column called 'race_time_ms' that:
    - Converts the column to a numeric data type
    - Replaces any non-numeric values with NaN

In [11]:
# Write your answer here

print(results.dtypes)

# many different columns that have an object data type, 
# but should be numeric, require conversion - specifically
# number, milliseconds, fastestLap, and rank.

milli_subset = results.query("milliseconds.str.isnumeric() == False")
display(milli_subset)

milli_unique = pd.unique(milli_subset["milliseconds"])
print(milli_unique)

list_old = ['\\N']
list_new = [np.nan]
results["race_time_ms"] = results["milliseconds"].replace(list_old,list_new)

results["race_time_ms"] = pd.to_numeric(results["race_time_ms"])
results["race_time_ms"]

resultId              int64
raceId                int64
driverId              int64
constructorId         int64
number               object
grid                  int64
position             object
positionText         object
positionOrder         int64
points              float64
laps                  int64
time                 object
milliseconds         object
fastestLap           object
rank                float64
fastestLapTime       object
fastestLapSpeed      object
statusId              int64
race_time_ms        float64
rank_clean           object
finish_category    category
dtype: object

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,race_time_ms,rank_clean,finish_category
5,6,18,6,3,8,13,6,6,6,3.0,...,\N,\N,50,14.0,1:29.639,212.974,11,NaN,14,Midfield
6,7,18,7,5,14,17,7,7,7,2.0,...,\N,\N,22,12.0,1:29.534,213.224,5,NaN,12,Midfield
7,8,18,8,6,1,15,8,8,8,1.0,...,\N,\N,20,4.0,1:27.903,217.180,5,NaN,4,Points
8,9,18,9,2,4,2,\N,R,9,0.0,...,\N,\N,15,9.0,1:28.753,215.100,4,NaN,9,Points
9,10,18,10,7,12,18,\N,R,10,0.0,...,\N,\N,23,13.0,1:29.558,213.166,3,NaN,13,Midfield
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,...,\N,\N,39,12.0,1:29.833,211.632,11,NaN,12,Midfield
25836,25842,1096,825,210,20,16,17,17,17,0.0,...,\N,\N,40,20.0,1:31.158,208.556,11,NaN,20,Midfield
25837,25843,1096,1,131,44,5,18,18,18,0.0,...,\N,\N,42,11.0,1:29.788,211.738,9,NaN,11,Midfield
25838,25844,1096,849,3,6,20,19,19,19,0.0,...,\N,\N,45,14.0,1:30.309,210.517,130,NaN,14,Midfield
25839,25845,1096,4,214,14,10,\N,R,20,0.0,...,\N,\N,24,17.0,1:30.579,209.889,47,NaN,17,Midfield

['\\N']

0        5690616.0
1        5696094.0
2        5698779.0
3        5707797.0
4        5708630.0
           ...
25835          NaN
25836          NaN
25837          NaN
25838          NaN
25839          NaN
Name: race_time_ms, Length: 25840, dtype: float64

### (b) Create Categorical Variables

- Create a new column called 'finish_category' that categorizes the race finish positions as follows:
    - Positions 1-3: 'Podium'
    - Positions 4-10: 'Points'
    - Positions 11-20: 'Midfield'
    - Positions >20: 'Backmarker'

Hint: Use the pd.cut() function

In [10]:
# Write your answer here

#results["rank"] = pd.to_numeric(results["rank"], errors="coerce")

#results['finish_category'] = pd.cut(results["rank"],
#                                    bins=[1, 3, 10, 20, float("inf")],
#                                    labels = ["Podium","Points","Midfield","Backmarker"])


bins_x = [1,3,10,20,float("inf")]
labels_x = ["Podium","Points","Midfield","Backmarker"]


results["rank_clean"] = results["rank"].replace("\\N",np.nan)
results["rank"] = pd.to_numeric(results["rank_clean"])

results["finish_category"] = pd.cut(results["rank"],
                                    bins = bins_x,
                                    labels = labels_x)
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,race_time_ms,rank_clean,finish_category
0,1,18,1,1,22,1,1,1,1,10.0,...,1:34:50.616,5690616,39,2.0,1:27.452,218.300,1,5690616.0,2,Podium
1,2,18,2,2,3,5,2,2,2,8.0,...,+5.478,5696094,41,3.0,1:27.739,217.586,1,5696094.0,3,Podium
2,3,18,3,3,7,7,3,3,3,6.0,...,+8.163,5698779,41,5.0,1:28.090,216.719,1,5698779.0,5,Points
3,4,18,4,4,5,11,4,4,4,5.0,...,+17.181,5707797,58,7.0,1:28.603,215.464,1,5707797.0,7,Points
4,5,18,5,1,23,3,5,5,5,4.0,...,+18.014,5708630,43,1.0,1:27.418,218.385,1,5708630.0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25835,25841,1096,854,210,47,12,16,16,16,0.0,...,\N,\N,39,12.0,1:29.833,211.632,11,NaN,12,Midfield
25836,25842,1096,825,210,20,16,17,17,17,0.0,...,\N,\N,40,20.0,1:31.158,208.556,11,NaN,20,Midfield
25837,25843,1096,1,131,44,5,18,18,18,0.0,...,\N,\N,42,11.0,1:29.788,211.738,9,NaN,11,Midfield
25838,25844,1096,849,3,6,20,19,19,19,0.0,...,\N,\N,45,14.0,1:30.309,210.517,130,NaN,14,Midfield
25839,25845,1096,4,214,14,10,\N,R,20,0.0,...,\N,\N,24,17.0,1:30.579,209.889,47,NaN,17,Midfield

### (c) Calculate Race Duration
- For rows where 'milliseconds' is available, create a new column <br>
'race_duration_minutes' that converts milliseconds to minutes by dividing <br>
by (1000*60).
- Display the average race duration by 'constructorId' for the top 5 <br>
constructors with the shortest average race times

In [14]:
# Write your answer here

#results["milliseconds"] = pd.to_numeric(results["milliseconds"], errors="coerce")

#results["race_duration_minutes"] = results["milliseconds"] / (1000*60)

#constructor_avg_duration = (results.groupby("constructorId")
#                            .agg(mean_time = ('race_duration_minutes','mean'))
#                            .sort_values("mean_time",ascending = False))

#constructor_avg_duration.head()

results["race_duration_minutes"] = results["race_time_ms"] / (1000*60)

constructor_duration = (results.groupby("constructorId")
                                    .agg(avg_duration = ("race_duration_minutes","mean"))
                                    .sort_values("avg_duration",ascending=True))

constructor_duration.head()

               avg_duration
constructorId
35                76.710777
29                77.604125
41                87.046767
16                89.428828
53                89.658852

### (d) Driver Performance Analysis

- Calculate the following statistics for each driver, grouped by 'driverId':
    - Average finishing position
    - Total points
    - Number of races completed
    - Best finishing position

- Sort the results by total points in descending order
- Display the top 10 drivers based on total points

In [ ]:
# Write your answer here

results["rank"] = pd.to_numeric(results["rank"], errors="coerce")
results["points"] = pd.to_numeric(results["points"], errors="coerce")

drivers_agg = (results.groupby("driverId")
               .agg(avg_finishing_position = ('rank','mean'),
                    total_points = ('points','sum'),
                    number_races = ('raceId','sum'),
                    best_finishing_position = ('rank','min'))
                .sort_values("total_points",ascending = False))

print(drivers_agg.head(10))

          avg_finishing_position  total_points  number_races  \
driverId
1                       4.600649        4396.5        239366
20                      6.402027        3098.0        237900
4                       7.229814        2061.0        207261
830                     5.177914        1983.5        164748
8                       6.731544        1873.0        200922
822                     6.980100        1778.0        198920
3                       7.376238        1594.5        114664
30                      7.366071        1566.0         85351
817                     9.521552        1307.0        225704
18                      8.835443        1235.0        128227

          best_finishing_position
driverId
1                             0.0
20                            0.0
4                             0.0
830                           0.0
8                             0.0
822                           0.0
3                             0.0
30                            1.0
817                           0.0
18                            0.0

### (e) Linear Regression
Create a linear regression model that predicts 'points' based on 'grid' (starting position) and 'laps' completed <br>
Use the following steps:

- Clean the data to remove any non-numeric values and missing values
- Create the regression formula using smf.ols 
- Display the summary of the regression model using model.summary()

What is the predicted points for a driver starting in position 3 and completing 55 laps?

Hint: Use ```.dropna()''' to remove missing values from the points, grid, and laps <br>
variables.

In [93]:
# Write your answer here
results_clean = results[['points','grid','laps']].dropna()

model = smf.ols(formula = 'points ~ grid + laps', data = results_clean).fit(cov_type = "HC1")
print(model.summary())


# predicted points for a driver starting in position 3 and completing 55 laps?
#intercept = 2.5841
#grid = -0.2248	
#laps = 0.0393	

result = 2.5841 - (0.2248*3) + (0.0393*55)
print(result)

#expected position is 4.0712

                            OLS Regression Results
==============================================================================
Dep. Variable:                 points   R-squared:                       0.215
Model:                            OLS   Adj. R-squared:                  0.215
Method:                 Least Squares   F-statistic:                     2248.
Date:                Mon, 24 Mar 2025   Prob (F-statistic):               0.00
Time:                        21:24:11   Log-Likelihood:                -70440.
No. Observations:               25840   AIC:                         1.409e+05
Df Residuals:                   25837   BIC:                         1.409e+05
Df Model:                           2
Covariance Type:                  HC1
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.5841      0.054     47.922      0.000       2.478       2.690
grid          -0.2248      0.004    -61.879      0.000      -0.232      -0.218
laps           0.0393      0.001     48.742      0.000       0.038       0.041
==============================================================================
Omnibus:                    15818.159   Durbin-Watson:                   0.715
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           183648.109
Skew:                           2.804   Prob(JB):                         0.00
Kurtosis:                      14.795   Cond. No.                         130.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
4.0712